# Generated by Django 4.2.7 on 2023-11-16 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_code', models.PositiveIntegerField(blank=True, unique=True)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_notes', models.TextField()),
                ('job_location', models.CharField(max_length=100)),
                ('job_mode', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote'), ('Onsite', 'Onsite')], max_length=20)),
                ('job_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Hold', 'Hold'), ('Upcoming', 'Upcoming')], default='Open', max_length=20)),
                ('job_work_hours', models.TextField()),
                ('job_type', models.CharField(choices=[('FT', 'FT'), ('Cont', 'Con'), ('C2H', 'C2H'), ('Temp', 'Temp'), ('Intern', 'Intern')], max_length=20)),
                ('job_priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('job_attachment', models.FileField(blank=True, null=True, upload_to='job_attachments/')),
                ('job_minimum_experience', models.PositiveIntegerField(blank=True)),
                ('job_maximum_experience', models.PositiveIntegerField(blank=True)),
                ('job_harvestor_string', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('job_pay_rate', models.PositiveIntegerField(blank=True)),
                ('job_bill_rate', models.PositiveIntegerField(blank=True)),
                ('job_salary_max', models.PositiveIntegerField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
