# Generated by Django 4.2.7 on 2023-11-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_harvestor_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
