# Generated by Django 4.2.7 on 2023-11-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_job_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_bill_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_maximum_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_minimum_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_pay_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_salary_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
